import { useState } from "react";
import { Link } from "react-router-dom";
import { useCart } from "../context/CartContext";
import { useAuth } from "../context/AuthContext";
import api from "../api/client";

export default function CheckoutPage() {
  const { items, subtotal, clearCart } = useCart();
  const { user } = useAuth();
  const [placed, setPlaced] = useState(false);
  const [error, setError] = useState<string | null>(null);
  if (placed) return <main className="checkout-page confirmation"><span className="confirmation-mark">✓</span><p className="eyebrow">Order received</p><h1>Thank you for shopping with us.</h1><p>We’ve sent your order confirmation to your inbox. Your good things will be on their way soon.</p><Link to="/shop" className="btn btn-primary">Continue shopping</Link></main>;
  if (!items.length) return <main className="checkout-page empty-cart"><h1>Your bag is empty.</h1><Link to="/shop" className="btn btn-primary">Browse the shop</Link></main>;
  return <main className="checkout-page"><p className="eyebrow">Checkout</p><h1>Almost yours.</h1>{!user && <p className="comment-error">Please <Link to="/login">log in</Link> before placing an order.</p>}<form className="checkout-layout" onSubmit={async (event) => { event.preventDefault(); if (!user) return; setError(null); const form = new FormData(event.currentTarget); try { await api.post("/orders", { items: items.map(({ product, quantity }) => ({ productId: product.id, quantity })), shipping: { firstName: form.get("firstName"), lastName: form.get("lastName"), address: form.get("address"), city: form.get("city"), postalCode: form.get("postalCode") } }); setPlaced(true); clearCart(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to place order."); } }}><section className="checkout-form"><h2>Delivery details</h2><div className="form-row"><label>First name<input name="firstName" required /></label><label>Last name<input name="lastName" required /></label></div><label>Email address<input type="email" value={user?.email ?? ""} readOnly required /></label><label>Address<input name="address" required /></label><div className="form-row"><label>City<input name="city" required /></label><label>Postal code<input name="postalCode" required /></label></div><h2>Payment</h2><p>Payment integration can be connected once a provider such as Stripe is configured.</p>{error && <p className="comment-error">{error}</p>}<label>Card number<input inputMode="numeric" placeholder="1234 1234 1234 1234" required /></label><div className="form-row"><label>Expiry<input placeholder="MM / YY" required /></label><label>Security code<input inputMode="numeric" required /></label></div><button className="btn btn-primary" type="submit" disabled={!user}>Place order · ${subtotal.toFixed(2)}</button></section><aside className="order-summary checkout-summary"><h2>In your bag</h2>{items.map(({ product, quantity }) => <div className="checkout-product" key={product.id}><span>{quantity} × {product.name}</span><strong>${(product.price * quantity).toFixed(2)}</strong></div>)}<div className="summary-total"><span>Total</span><strong>${subtotal.toFixed(2)}</strong></div></aside></form></main>;
}
